import * as THREE from 'three';
import * as CANNON from 'cannon-es';
import {roundedGeometry} from './rounded-geometry.mjs';
import {ConvexGeometry} from 'three/addons/geometries/ConvexGeometry.js';
const $=id=>document.getElementById(id), TYPES=[4,6,8,10,12,20,100,1000];
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const settings={surface:'midnight',color:'#e3ba72',sound:true,haptic:true,battery:false,force:1,faceStyle:'classic',dieSize:1.1,...read('atelier-settings',{})};
let history=read('atelier-history',[]).slice(0,100),presets=read('atelier-presets',[{name:'Iniciativa',pool:[20],mod:0,mode:'normal'},{name:'Bola de fuego',pool:[6,6,6,6,6,6,6,6],mod:0,mode:'normal'}]);
if(presets[0]?.name==='Initiative')presets[0].name='Iniciativa';if(presets[1]?.name==='Boule de feu')presets[1].name='Bola de fuego';
const PALETTE=[["#f4f3ef","Blanco"],["#202329","Negro"],["#b51f32","Rojo"],["#e3ba72","Ámbar"],["#e9e7dd","Marfil"],["#61b7bf","Glaciar"],["#b995d7","Amatista"]];
let poolColors=[[settings.color]];
let pool=[20],dice=[],rolling=false,dirty=true,lastResult=null,rollStart=0,quiet=0,rollMode='normal',world,scene,camera,renderer,ground,arenaWidth=16,arenaDepth=11,walls=[],audioContext,drag=null,rollResolve,tableFrame,mobileScale=1;
const dieScale=()=>Number(settings.dieSize)*mobileScale;
const store=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{toast('No se pudo guardar: almacenamiento no disponible.')}};
let toastTimer;function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500)}
const rnd=()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296;
const formatPool=arr=>TYPES.map(t=>{let n=arr.filter(x=>x===t).length;return n?`${n}d${t}`:''}).filter(Boolean).join(' + ')||'Sin dados';
const modifier=()=>{let n=Number($('modifier').value);return Number.isFinite(n)?Math.max(-999,Math.min(999,Math.trunc(n))):0};
function persistSettings(){store('atelier-settings',settings)}
function sound(impact){if(!settings.sound||!audioContext||impact<1.5)return;let t=audioContext.currentTime;let o=audioContext.createOscillator(),g=audioContext.createGain();o.type='triangle';o.frequency.setValueAtTime(150+rnd()*100,t);o.frequency.exponentialRampToValueAtTime(60,t+.055);g.gain.setValueAtTime(Math.min(impact*.009,.085),t);g.gain.exponentialRampToValueAtTime(.001,t+.06);o.connect(g);g.connect(audioContext.destination);o.start(t);o.stop(t+.065)}
function unlockAudio(){try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume()}catch{}}
// Face planes and values match the convex collider; visual bevels round its corners.
function shapeData(type){let geo;if(type===4)geo=new THREE.TetrahedronGeometry(1.02);if(type===6)geo=new THREE.BoxGeometry(1.36,1.36,1.36);if(type===8)geo=new THREE.OctahedronGeometry(1.03);if(type===12)geo=new THREE.DodecahedronGeometry(1.05);if(type===20)geo=new THREE.IcosahedronGeometry(1.07);if(type===10){let points=[new THREE.Vector3(0,1.15,0),new THREE.Vector3(0,-1.15,0)],a=1.15*(1-Math.cos(Math.PI/5))/(1+Math.cos(Math.PI/5));for(let i=0;i<10;i++)points.push(new THREE.Vector3(Math.cos(i*Math.PI/5),i%2===0?a:-a,Math.sin(i*Math.PI/5)));geo=new ConvexGeometry(points)}if(geo.index)geo=geo.toNonIndexed();let vertices=[],tris=[],pos=geo.attributes.position;for(let i=0;i<pos.count;i+=3){let face=[];for(let j=0;j<3;j++){let v=new THREE.Vector3().fromBufferAttribute(pos,i+j);let index=vertices.findIndex(p=>p.distanceTo(v)<.0001);if(index<0){index=vertices.length;vertices.push(v)}face.push(index)}tris.push(face)}let faces=[];for(const tri of tris){let a=vertices[tri[0]],b=vertices[tri[1]],c=vertices[tri[2]],normal=b.clone().sub(a).cross(c.clone().sub(a)).normalize(),plane=normal.dot(a);let f=faces.find(f=>f.normal.dot(normal)>.99999&&Math.abs(f.plane-plane)<.0001);if(!f){f={normal,plane,ids:new Set()};faces.push(f)}tri.forEach(i=>f.ids.add(i))}faces.forEach((f,i)=>{f.center=[...f.ids].reduce((s,j)=>s.add(vertices[j]),new THREE.Vector3()).multiplyScalar(1/f.ids.size);let u=vertices[[...f.ids][0]].clone().sub(f.center).normalize(),v=f.normal.clone().cross(u);f.indices=[...f.ids].sort((a,b)=>{let pa=vertices[a].clone().sub(f.center),pb=vertices[b].clone().sub(f.center);return Math.atan2(pa.dot(v),pa.dot(u))-Math.atan2(pb.dot(v),pb.dot(u))});f.value=type===10?i:i+1});if(type!==4){let assigned=new Set(),low=type===10?0:1,high=type===10?9:type;for(const f of faces){if(assigned.has(f))continue;let opposite=faces.filter(g=>g!==f&&!assigned.has(g)).sort((a,b)=>a.normal.dot(f.normal)-b.normal.dot(f.normal))[0];f.value=low++;assigned.add(f);if(opposite){opposite.value=high--;assigned.add(opposite)}}}geo.dispose();return {vertices,faces,type}}
const shapes=new Map([4,6,8,10,12,20].map(t=>[t,shapeData(t)]));
function roman(n){let r='';for(const[v,c]of[[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']])while(n>=v){r+=c;n-=v}return r}
function labelTexture(value,pips=false,color=settings.color){let c=document.createElement('canvas');c.width=c.height=256;let ctx=c.getContext('2d'),rgb=color.match(/\w\w/g).map(h=>parseInt(h,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4),luminance=.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2],dark=luminance<.179;ctx.fillStyle=dark?'#ffffff':'#080b0d';if(pips){let points={1:[[0,0]],2:[[-1,-1],[1,1]],3:[[-1,-1],[0,0],[1,1]],4:[[-1,-1],[-1,1],[1,-1],[1,1]],5:[[-1,-1],[-1,1],[0,0],[1,-1],[1,1]],6:[[-1,-1],[-1,0],[-1,1],[1,-1],[1,0],[1,1]]}[value];for(const[x,y]of points){ctx.beginPath();ctx.arc(128+x*65,128+y*65,24,0,Math.PI*2);ctx.fill()}}else{let text=settings.faceStyle==='roman'&&typeof value==='number'&&value>0?roman(value):String(value);ctx.font=`700 ${text.length>3?83:text.length>2?100:text.length>1?128:152}px Georgia`;if(ctx.measureText(text).width>225){let fontSize=parseFloat(ctx.font.split(' ')[1]);ctx.font=`700 ${fontSize*225/ctx.measureText(text).width}px Georgia`}ctx.textAlign='center';ctx.textBaseline='middle';ctx.strokeStyle=dark?'rgba(0,0,0,.4)':'rgba(255,255,255,.3)';ctx.lineWidth=2;ctx.strokeText(text,128,134);ctx.fillText(text,128,134);if(settings.faceStyle!=='roman'&&(value===6||value===9))ctx.fillRect(100,212,56,6)}let texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;return texture}
const textures=new Map();function tex(v,pips=false,color=settings.color){let key=[v,typeof v,pips,color,settings.faceStyle].join(':');if(!textures.has(key))textures.set(key,labelTexture(v,pips,color));return textures.get(key)}
function makeDie(type,logicalIndex,place,colorIndex){let color=poolColors[logicalIndex][colorIndex],size=dieScale(),base=shapes.get(type),data={...base,vertices:base.vertices.map(v=>v.clone().multiplyScalar(size)),faces:base.faces.map(f=>({...f,center:f.center.clone().multiplyScalar(size)}))},group=new THREE.Group();let {geometry,borderGeometry}=roundedGeometry(data,(type===6?.105:type===4?.065:.055)*size);let mesh=new THREE.Mesh(geometry,new THREE.MeshPhysicalMaterial({color,roughness:.3,metalness:.04,clearcoat:.4,clearcoatRoughness:.24}));mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);let dark=['#202329','#b51f32'].includes(color);let edges=new THREE.LineSegments(borderGeometry,new THREE.LineBasicMaterial({color:dark?'#e7eaf0':'#29303a',transparent:true,opacity:dark?.24:.16,depthWrite:false}));group.add(edges);
for(const f of data.faces){if(type===4){for(const vertexId of f.indices){let p=data.vertices[vertexId].clone().lerp(f.center,.37).addScaledVector(f.normal,.012),label=new THREE.Mesh(new THREE.PlaneGeometry(.43*size,.43*size),new THREE.MeshBasicMaterial({map:tex(vertexId+1,false,color),transparent:true,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2}));label.userData.paint={value:vertexId+1,pips:false};label.position.copy(p);label.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),f.normal);group.add(label)}}else{let size=(type===20?.67:type===12?.8:type===10?.7:type===6?.98:.84)*dieScale();let label=new THREE.Mesh(new THREE.PlaneGeometry(size,size),new THREE.MeshBasicMaterial({map:tex(place>1?String(f.value*place).padStart(place===100?3:2,'0'):pool[logicalIndex]>=100?String(f.value):f.value,settings.faceStyle==='pips'&&type===6,color),transparent:true,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2}));label.userData.paint={value:place>1?String(f.value*place).padStart(place===100?3:2,'0'):pool[logicalIndex]>=100?String(f.value):f.value,pips:settings.faceStyle==='pips'&&type===6};label.position.copy(f.center).addScaledVector(f.normal,.009);label.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),f.normal);group.add(label)}}
let shape=new CANNON.ConvexPolyhedron({vertices:data.vertices.map(v=>new CANNON.Vec3(v.x,v.y,v.z)),faces:data.faces.map(f=>f.indices)});let body=new CANNON.Body({mass:1,shape,material:dieMaterial,linearDamping:.25,angularDamping:.28,allowSleep:true,sleepSpeedLimit:.13,sleepTimeLimit:.65});body.addEventListener('collide',e=>sound(Math.abs(e.contact.getImpactVelocityAlongNormal())));world.addBody(body);scene.add(group);let d={type,logicalIndex,place,colorIndex,color,edges,data,body,group,mesh,pinned:false,value:null};mesh.userData.die=d;return d}
let dieMaterial,floorMaterial;
function init(){scene=new THREE.Scene();scene.background=new THREE.Color('#142c33');camera=new THREE.PerspectiveCamera(37,1,.1,100);camera.position.set(0,17,9);camera.lookAt(0,0,0);renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;$('canvas-host').appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight('#e5eeff','#33413b',2.2));let light=new THREE.DirectionalLight('#ffedce',3.7);light.position.set(-5,12,6);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-16,right:16,top:16,bottom:-16});light.shadow.normalBias=.025;light.shadow.bias=-.0002;scene.add(light);let rim=new THREE.DirectionalLight('#c4daff',1.1);rim.position.set(7,6,-5);scene.add(rim);
world=new CANNON.World({gravity:new CANNON.Vec3(0,-24,0),allowSleep:true});world.solver.iterations=22;world.broadphase=new CANNON.SAPBroadphase(world);dieMaterial=new CANNON.Material('dice');floorMaterial=new CANNON.Material('felt');world.addContactMaterial(new CANNON.ContactMaterial(dieMaterial,floorMaterial,{friction:.45,restitution:.27}));world.addContactMaterial(new CANNON.ContactMaterial(dieMaterial,dieMaterial,{friction:.32,restitution:.36}));let floor=new CANNON.Body({mass:0,material:floorMaterial,shape:new CANNON.Plane()});floor.quaternion.setFromEuler(-Math.PI/2,0,0);world.addBody(floor);
let noise=document.createElement('canvas');noise.width=noise.height=256;let ctx=noise.getContext('2d'),img=ctx.createImageData(256,256);for(let i=0;i<img.data.length;i+=4){let n=110+Math.random()*55;img.data[i]=img.data[i+1]=img.data[i+2]=n;img.data[i+3]=255}ctx.putImageData(img,0,0);let texture=new THREE.CanvasTexture(noise);texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(12,12);ground=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({color:'#163039',roughness:1,map:texture,bumpMap:texture,bumpScale:.015}));ground.rotation.x=-Math.PI/2;ground.position.y=-.015;ground.receiveShadow=true;scene.add(ground);new ResizeObserver(resize).observe($('canvas-host'));applySurface();resize();syncDice();renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointermove',pointerMove);renderer.domElement.addEventListener('pointerup',pointerUp);renderer.domElement.addEventListener('pointercancel',pointerUp);$('loading').remove();requestAnimationFrame(frame)}
function resize(){let r=$('canvas-host').getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;let narrow=camera.aspect<1.15,handheld=Math.min(window.innerWidth,window.innerHeight)<=600;const nextScale=handheld?1.5:1;if(nextScale!==mobileScale){const ratio=nextScale/mobileScale;mobileScale=nextScale;for(const d of dice){d.group.scale.multiplyScalar(ratio);d.data.vertices.forEach(v=>v.multiplyScalar(ratio));d.data.faces.forEach(f=>f.center.multiplyScalar(ratio));for(const shape of d.body.shapes){shape.vertices.forEach(v=>v.scale(ratio,v));shape.updateBoundingSphereRadius();shape.worldVerticesNeedsUpdate=true;shape.worldFaceNormalsNeedsUpdate=true}d.body.updateBoundingRadius();d.body.updateMassProperties();d.body.aabbNeedsUpdate=true;d.body.wakeUp()}}const count=pool.reduce((n,t)=>n+(t===100?2:t===1000?3:1),0),crowd=Math.max(1,Math.sqrt(count/6));arenaWidth=handheld?(narrow?7.5:11)*crowd:(narrow?9.5:Math.min(19,12*camera.aspect/1.5));arenaDepth=handheld?(narrow?(camera.aspect<.65?17:11.5):7.5)*crowd:(narrow?12:10);
// A seated observer's oblique view. Fit the entire physical tray, including
// its near edge, instead of clipping dice when the screen changes shape.
camera.fov=43;const target=new THREE.Vector3(0,.65,0),direction=new THREE.Vector3(.025,handheld&&narrow?.92:.78,handheld&&narrow?.4:.63).normalize();let distance=handheld?8:15;for(let i=0;i<60;i++){camera.position.copy(target).addScaledVector(direction,distance);camera.lookAt(target);camera.updateProjectionMatrix();camera.updateMatrixWorld();let fits=true;for(const x of [-arenaWidth/2-.3,arenaWidth/2+.3])for(const z of [-arenaDepth/2-.3,arenaDepth/2+.3])for(const y of [0,handheld?2.5:2]){let v=new THREE.Vector3(x,y,z).project(camera);if(Math.abs(v.x)>(handheld?.97:.9)||v.y>(handheld?.88:.82)||v.y<(handheld?-.82:-.77))fits=false}if(fits)break;distance+=.5}
if(tableFrame){scene.remove(tableFrame);tableFrame.traverse(o=>{o.geometry?.dispose();o.material?.dispose()})}tableFrame=new THREE.Group();const rimMaterial=new THREE.MeshStandardMaterial({color:'#26363c',roughness:.45,metalness:.3});for(const[x,z,w,d]of[[0,-arenaDepth/2-.17,arenaWidth+.65,.32],[0,arenaDepth/2+.17,arenaWidth+.65,.32],[-arenaWidth/2-.17,0,.32,arenaDepth],[arenaWidth/2+.17,0,.32,arenaDepth]]){let rim=new THREE.Mesh(new THREE.BoxGeometry(w,.35,d),rimMaterial.clone());rim.position.set(x,.13,z);rim.castShadow=true;rim.receiveShadow=true;tableFrame.add(rim)}rimMaterial.dispose();scene.add(tableFrame);
walls.forEach(b=>world.removeBody(b));walls=[];for(const[x,z,hx,hz]of[[arenaWidth/2+1,0,1,25],[-arenaWidth/2-1,0,1,25],[0,arenaDepth/2+1,25,1],[0,-arenaDepth/2-1,25,1]]){let b=new CANNON.Body({mass:0,shape:new CANNON.Box(new CANNON.Vec3(hx,12,hz)),position:new CANNON.Vec3(x,10,z),material:floorMaterial});world.addBody(b);walls.push(b)}for(const d of dice){d.body.position.x=Math.max(-arenaWidth/2+dieScale()*1.1,Math.min(arenaWidth/2-dieScale()*1.1,d.body.position.x));d.body.position.z=Math.max(-arenaDepth/2+dieScale()*1.1,Math.min(arenaDepth/2-dieScale()*1.1,d.body.position.z));d.body.wakeUp()}dirty=true}
function syncDice(){resize();poolColors=pool.map((t,i)=>Array.from({length:t===100?2:t===1000?3:1},(_,k)=>PALETTE.some(([c])=>c===poolColors[i]?.[k])?poolColors[i][k]:settings.color));dice.forEach(d=>{scene.remove(d.group);world.removeBody(d.body);d.group.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose()})});dice=[];pool.forEach((t,i)=>{let n=t===100?2:t===1000?3:1;for(let k=0;k<n;k++)dice.push(makeDie(t>=100?10:t,i,t>=100?10**(n-k-1):1,k))});let cols=Math.max(1,Math.min(Math.floor(arenaWidth/(2.3*dieScale())),dice.length));dice.forEach((d,i)=>{d.body.position.set((i%cols-(cols-1)/2)*2.3*dieScale(),1.8+Math.floor(i/(cols*4))*2.3,(Math.floor(i/cols)-(Math.ceil(dice.length/cols)-1)/2)*2.3*dieScale());d.body.quaternion.setFromEuler(.24+i*.5,.4+i,.15);d.body.wakeUp()});lastResult=null;$('table-total').textContent='';$('total').textContent='—';$('breakdown').textContent='Todo listo para empezar';$('dice-results').replaceChildren();$('physics-status').textContent='Física en tiempo real';updatePicker();renderDieColors();dirty=true}
function updatePicker(){for(const b of $('dice-picker').children){let n=pool.filter(t=>t===Number(b.dataset.type)).length;b.classList.toggle('active',!!n);b.querySelector('b').textContent=n||'';b.querySelector('b').hidden=!n} $('selection-summary').textContent=formatPool(pool);$('remove-dice').replaceChildren();for(const t of TYPES){let count=pool.filter(x=>x===t).length;if(!count)continue;let remove=document.createElement('button');remove.textContent=`− d${t}`;remove.setAttribute('aria-label',`Quitar un d${t}`);remove.disabled=rolling;remove.onclick=()=>{if(rolling)return;poolColors.splice(pool.lastIndexOf(t),1);pool.splice(pool.lastIndexOf(t),1);rollMode='normal';$('roll-mode').value='normal';syncDice()};$('remove-dice').append(remove)}$('table-count').textContent=`${dice.length} dado${dice.length!==1?'s':''} en la mesa`;document.querySelectorAll('#die-colors select').forEach(el=>el.disabled=rolling);$('table-roll').disabled=rolling||!dice.length;$('table-roll').textContent=rolling?'Lanzando…':'Lanzar todos ↗';$('roll').disabled=rolling||!dice.length;$('clear').disabled=rolling;for(const b of $('dice-picker').children)b.disabled=rolling;$('roll-mode').disabled=rolling;$('modifier').disabled=rolling;$('mod-minus').disabled=rolling;$('mod-plus').disabled=rolling;$('roll').innerHTML=rolling?'Lanzando… <span>↻</span>':'Lanzar dados <span>↗</span>'}
function beginRoll(){dice.forEach(d=>d.recovery=0);rolling=true;quiet=0;rollStart=performance.now();$('physics-status').textContent='Los dados están rodando';$('breakdown').textContent='Esperando a que se detengan…';$('table-total').textContent='Rodando…';$('total').textContent='…';updatePicker();dirty=true}
function launch(){if(rolling||!dice.length)return;if(dice.every(d=>d.pinned)){toast('Libera un dado para volver a lanzar.');return}unlockAudio();beginRoll();let f=Number(settings.force),movable=dice.filter(d=>!d.pinned),spacing=2.15*dieScale(),cols=Math.max(1,Math.min(3,Math.floor((arenaWidth-1)/spacing),movable.length)),depthRows=Math.max(1,Math.min(3,Math.floor((arenaDepth-2)/spacing),Math.ceil(movable.length/cols))),originX=-Math.min(1.2,arenaWidth*.1),sharedX=(.7+rnd())*f,sharedZ=-(3.5+rnd()*1.5)*f;
movable.forEach((d,i)=>{d.body.type=CANNON.Body.DYNAMIC;d.body.mass=1;d.body.updateMassProperties();let col=i%cols,row=Math.floor(i/cols)%depthRows,layer=Math.floor(i/(cols*depthRows));let x=originX+(col-(cols-1)/2)*spacing,z=Math.min(arenaDepth/2-dieScale()*1.2,(depthRows-1)*spacing/2+arenaDepth*.08)-row*spacing;d.body.position.set(Math.max(-arenaWidth/2+dieScale()*1.1,Math.min(arenaWidth/2-dieScale()*1.1,x)),2.8+layer*spacing,z);d.body.quaternion.setFromEuler(rnd()*6.28,rnd()*6.28,rnd()*6.28);d.body.velocity.set(sharedX+(col-(cols-1)/2)*1.2+(rnd()-.5)*2,3.6*f+(rnd()-.5),sharedZ+(rnd()-.5)*3);d.body.angularVelocity.set(-10*f+(rnd()-.5)*9,(rnd()-.5)*14,(rnd()-.5)*13);d.body.wakeUp()});return new Promise(resolve=>rollResolve=resolve)}
function readDie(d){let q=new THREE.Quaternion(d.body.quaternion.x,d.body.quaternion.y,d.body.quaternion.z,d.body.quaternion.w);if(d.type===4){let scores=d.data.vertices.map((v,i)=>({value:i+1,score:v.clone().normalize().applyQuaternion(q).y})).sort((a,b)=>b.score-a.score);return {value:scores[0].value,alignment:scores[0].score}}let faces=d.data.faces.map(f=>({value:f.value,alignment:f.normal.clone().applyQuaternion(q).y})).sort((a,b)=>b.alignment-a.alignment);return faces[0]}
function finish(){let cocked=dice.filter(d=>!d.pinned&&readDie(d).alignment<.965);if(cocked.length){cocked.forEach(d=>{d.recovery=(d.recovery||0)+1;let best={x:0,z:0,score:-1},margin=dieScale()*1.2;for(let i=0;i<48;i++){let x=(rnd()-.5)*(arenaWidth-2*margin),z=(rnd()-.5)*(arenaDepth-2*margin),score=Math.min(...dice.filter(other=>other!==d).map(other=>Math.hypot(x-other.body.position.x,z-other.body.position.z)));if(score>best.score)best={x,z,score}}if(d.recovery>=1){d.body.position.set(best.x,dieScale()*2.7,best.z);d.body.quaternion.setFromEuler(rnd()*6.28,rnd()*6.28,rnd()*6.28);d.body.velocity.set(0,1,0)}else d.body.velocity.set(Math.max(-5,Math.min(5,(best.x-d.body.position.x)*2)),6,Math.max(-5,Math.min(5,(best.z-d.body.position.z)*2)));d.body.angularVelocity.set(rnd()*5,3,rnd()*5);d.body.wakeUp()});quiet=0;$('physics-status').textContent='Relanzando un dado inclinado';return}rolling=false;dice.forEach(d=>{d.value=readDie(d).value});let values=pool.map((t,i)=>{let ds=dice.filter(d=>d.logicalIndex===i);let v=ds.reduce((s,d)=>s+d.value*d.place,0);return t>=100?(v||t):t===10?(v||10):v});let mod=modifier(),base=values.reduce((s,v)=>s+v,0),selected=-1;if(rollMode!=='normal'){base=rollMode==='advantage'?Math.max(...values):Math.min(...values);selected=values.indexOf(base)}let total=base+mod;let expression=values.join(' + ');if(rollMode!=='normal')expression=`${rollMode==='advantage'?'Mayor':'Menor'} de ${values.join(' y ')}`;if(mod)expression+=mod>0?` + ${mod}`:` − ${Math.abs(mod)}`;lastResult={time:new Date().toISOString(),formula:formatPool(pool),values,total,mod,mode:rollMode,expression,pool:[...pool]};history.unshift(lastResult);history=history.slice(0,100);store('atelier-history',history);$('table-total').textContent=`Total: ${total}`;$('total').textContent=total;$('breakdown').textContent=expression;$('announcement').textContent=`Resultado: ${total}. ${expression}`;$('physics-status').textContent='Tirada completada';$('history-count').textContent=history.length;renderResults(selected);updatePicker();if(settings.haptic)navigator.vibrate?.(25);rollResolve?.(lastResult);rollResolve=null;dirty=true}
function renderResults(selected=-1){$('dice-results').replaceChildren();dice.forEach((d,i)=>{let b=document.createElement('button');b.className='result-chip'+(d.pinned?' pinned':'')+(selected>=0&&d.logicalIndex!==selected?' discarded':'');let label=d.place>1?`×${d.place}`:`d${d.type}`;b.innerHTML=`<small>${label}</small>${d.value===null?'—':d.type===10&&pool[d.logicalIndex]===10?(d.value||10):d.value}${d.pinned?' · fijo':''}`;b.title=d.pinned?'Liberar dado':'Conservar dado en la siguiente tirada';b.setAttribute('aria-pressed',d.pinned);b.onclick=()=>{if(rolling)return;d.pinned=!d.pinned;d.body.mass=d.pinned?0:1;d.body.type=d.pinned?CANNON.Body.STATIC:CANNON.Body.DYNAMIC;d.body.updateMassProperties();d.body.velocity.setZero();d.body.angularVelocity.setZero();d.body.wakeUp();renderResults(selected);dirty=true};$('dice-results').append(b)})}
let lastFrame=0,acc=0;function frame(now){requestAnimationFrame(frame);if(document.hidden){lastFrame=now;return}let elapsed=Math.min((now-lastFrame)/1000,.1);if(settings.battery&&elapsed<1/32)return;lastFrame=now;if(drag){let t=Math.min(1,(now-drag.liftStart)/180);drag.d.body.position.y=drag.fromY+(4.2-drag.fromY)*(1-(1-t)**3)}let active=rolling||drag||dice.some(d=>d.body.sleepState!==CANNON.Body.SLEEPING&& !d.pinned);if(active){world.step(1/60,elapsed,6);for(const d of dice){if(d.body.position.y < -2 || Math.abs(d.body.position.x)>arenaWidth || Math.abs(d.body.position.z)>arenaDepth){d.body.position.set(0,4,0);d.body.velocity.setZero();d.body.wakeUp()}d.group.position.copy(d.body.position);d.group.quaternion.copy(d.body.quaternion)}dirty=true}if(rolling&&!drag){let stopped=dice.every(d=>d.pinned||(d.body.velocity.length()<.16&&d.body.angularVelocity.length()<.16));quiet=stopped?quiet+elapsed:0;if(quiet>.55)finish();else if(now-rollStart>18000){dice.filter(d=>!d.pinned).forEach(d=>{d.body.velocity.scale(.65,d.body.velocity);d.body.angularVelocity.scale(.65,d.body.angularVelocity)});rollStart=now-14000}}if(dirty){renderer.render(scene,camera);dirty=false}}
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2(),dragPlane=new THREE.Plane(new THREE.Vector3(0,1,0),-4.2);function hitPoint(e){let r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);let p=new THREE.Vector3();ray.ray.intersectPlane(dragPlane,p);return p}
function pointerDown(e){if(rolling)return;hitPoint(e);let hits=ray.intersectObjects(dice.map(d=>d.mesh));if(!hits.length)return;let d=hits[0].object.userData.die;if(d.pinned){toast('Libera este dado tocando su resultado.');return}unlockAudio();beginRoll();drag={d,fromY:d.body.position.y,liftStart:performance.now(),last:hitPoint(e),time:performance.now(),vx:0,vz:0};d.body.type=CANNON.Body.KINEMATIC;d.body.velocity.setZero();d.body.angularVelocity.setZero();renderer.domElement.setPointerCapture(e.pointerId);pointerMove(e)}
function pointerMove(e){if(!drag)return;let p=hitPoint(e),now=performance.now(),dt=Math.max(.016,(now-drag.time)/1000);p.x=Math.max(-arenaWidth/2+1,Math.min(arenaWidth/2-1,p.x));p.z=Math.max(-arenaDepth/2+1,Math.min(arenaDepth/2-1,p.z));drag.vx=Math.max(-14,Math.min(14,(p.x-drag.last.x)/dt));drag.vz=Math.max(-14,Math.min(14,(p.z-drag.last.z)/dt));drag.d.body.position.set(p.x,drag.d.body.position.y,p.z);drag.last=p;drag.time=now;dirty=true}
function pointerUp(){if(!drag)return;let {d,vx,vz,time}=drag;d.body.type=CANNON.Body.DYNAMIC;d.body.mass=1;d.body.updateMassProperties();let fresh=performance.now()-time<100;d.body.velocity.set(fresh?vx:0,1.5,fresh?vz:0);d.body.angularVelocity.set(vz*.8,3,-vx*.8);d.body.wakeUp();drag=null;quiet=0;rollStart=performance.now()}
function applySurface(){let cfg={midnight:['#163039','Fieltro · medianoche'],forest:['#1c443a','Fieltro · bosque'],wine:['#4b2636','Fieltro · burdeos']}[settings.surface]||['#163039','Fieltro · medianoche'];if(ground)ground.material.color.set(cfg[0]);$('surface-name').textContent=cfg[1];dirty=true}
function renderPresets(){$('presets').replaceChildren();presets.forEach((p,i)=>{let row=document.createElement('div');row.className='preset';let b=document.createElement('button');b.textContent=p.name;let small=document.createElement('small');small.textContent=formatPool(p.pool)+(p.mod?` ${p.mod>0?'+':''}${p.mod}`:'');b.append(small);b.onclick=()=>{if(rolling)return;pool=[...p.pool];poolColors=Array.isArray(p.colors)?p.colors.map(c=>[...c]):[];$('modifier').value=p.mod;rollMode=p.mode;$('roll-mode').value=p.mode;syncDice();toast(`Preparada: ${p.name}`)};let del=document.createElement('button');del.textContent='×';del.setAttribute('aria-label',`Eliminar ${p.name}`);del.onclick=()=>{presets.splice(i,1);store('atelier-presets',presets);renderPresets()};row.append(b,del);$('presets').append(row)})}
function renderHistory(){$('history-list').replaceChildren();if(!history.length){let p=document.createElement('p');p.className='muted';p.textContent='Tus tiradas aparecerán aquí.';$('history-list').append(p)}history.forEach(h=>{let row=document.createElement('div');row.className='history-item';let div=document.createElement('div');div.textContent=h.formula;let small=document.createElement('small');small.textContent=h.expression+' · '+new Date(h.time).toLocaleString('es-CL',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});div.append(small);let strong=document.createElement('strong');strong.textContent=h.total;row.append(div,strong);$('history-list').append(row)})}
for(const type of TYPES){let b=document.createElement('button');b.dataset.type=type;b.className='die-button';b.setAttribute('aria-label',`Añadir d${type}`);b.innerHTML=`<svg viewBox="0 0 36 36" aria-hidden="true"><path d="M18 3 32 11 29 28 18 34 5 27 3 11Z M18 3 10 24 32 11 18 34 10 24 3 11 29 28 10 24"/></svg>d${type}<b hidden></b>`;b.onclick=()=>{if(rolling)return;let current=pool.reduce((s,t)=>s+(t===100?2:t===1000?3:1),0),add=type===100?2:type===1000?3:1;if(current+add>20)return toast('Máximo 20 dados físicos por tirada.');if(rollMode!=='normal'){rollMode='normal';$('roll-mode').value='normal';pool=[];poolColors=[]}poolColors.push(Array(type===100?2:type===1000?3:1).fill(settings.color));pool.push(type);syncDice()};b.oncontextmenu=e=>{e.preventDefault();if(rolling)return;let i=pool.lastIndexOf(type);if(i>=0){poolColors.splice(i,1);pool.splice(i,1);rollMode='normal';$('roll-mode').value='normal';syncDice()}};$('dice-picker').append(b)}
$('roll').onclick=launch;$('clear').onclick=()=>{pool=[];poolColors=[];rollMode='normal';$('roll-mode').value='normal';syncDice()};$('mod-minus').onclick=()=>{$('modifier').value=Math.max(-999,modifier()-1)};$('mod-plus').onclick=()=>{$('modifier').value=Math.min(999,modifier()+1)};$('modifier').onchange=()=>{$('modifier').value=modifier()};$('roll-mode').onchange=e=>{rollMode=e.target.value;if(rollMode!=='normal'){pool=[20,20];poolColors=[[settings.color],[settings.color]];}syncDice()};document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','TEXTAREA','BUTTON','SUMMARY'].includes(e.target.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();launch()}});
$('settings-open').onclick=()=>$('settings').showModal();$('history-open').onclick=()=>{renderHistory();$('history').showModal()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('save-preset').onclick=()=>{if(!pool.length)return toast('Añade algún dado primero.');$('save-dialog').showModal()};$('save-form').onsubmit=e=>{e.preventDefault();let name=$('preset-name').value.trim();if(!name)return;presets.push({name,pool:[...pool],colors:poolColors.map(c=>[...c]),mod:modifier(),mode:rollMode});store('atelier-presets',presets);renderPresets();$('save-dialog').close();$('preset-name').value='';toast('Tirada guardada')};$('delete-history').onclick=()=>{if(confirm('¿Borrar el historial de este dispositivo?')){history=[];store('atelier-history',history);$('history-count').textContent=0;renderHistory()}};$('export').onclick=()=>{let blob=new Blob([JSON.stringify(history,null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='dados-3d-tiradas.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
for(const k of ['sound','haptic','battery']){$(k).checked=settings[k];$(k).onchange=e=>{settings[k]=e.target.checked;persistSettings()}}for(const k of ['surface','color','force']){$(k).value=settings[k];$(k).onchange=e=>{if(rolling&&k==='color'){e.target.value=settings[k];return toast('Espera a que termine la tirada.')}settings[k]=e.target.value;persistSettings();if(k==='surface')applySurface();if(k==='color')$('add-color').value=settings.color;dirty=true}}$('face-style').value=settings.faceStyle;$('face-style').onchange=e=>{if(rolling){e.target.value=settings.faceStyle;return toast('Espera a que termine la tirada.')}settings.faceStyle=e.target.value;persistSettings();syncDice()};$('die-size').value=settings.dieSize;$('die-size').onchange=e=>{if(rolling){e.target.value=settings.dieSize;return toast('Espera a que termine la tirada.')}settings.dieSize=Number(e.target.value);persistSettings();syncDice()};function syncFullscreen(){const expanded=!!document.fullscreenElement||$('table').classList.contains('table-expanded');$('table').classList.toggle('is-fullscreen',expanded);document.body.classList.toggle('table-is-expanded',expanded);$('table-exit').hidden=!expanded;resize()}
async function exitTable(){if(document.fullscreenElement)await document.exitFullscreen();$('table').classList.remove('table-expanded');syncFullscreen()}
$('table-roll').onclick=launch;$('table-exit').onclick=exitTable;document.addEventListener('fullscreenchange',syncFullscreen);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('table').classList.contains('table-expanded'))exitTable()});
$('fullscreen').onclick=async()=>{if(document.fullscreenElement||$('table').classList.contains('table-expanded'))return exitTable();try{if($('table').requestFullscreen){await $('table').requestFullscreen();syncFullscreen();return}}catch{}$('table').classList.add('table-expanded');syncFullscreen()};
let motionActive=false,lastShake=0;$('motion').onclick=async()=>{try{if(!window.DeviceMotionEvent)return toast('Este dispositivo no admite sensores de movimiento.');if(typeof DeviceMotionEvent.requestPermission==='function'&&await DeviceMotionEvent.requestPermission()!=='granted')return toast('No se concedió permiso de movimiento.');if(motionActive)return;window.addEventListener('devicemotion',e=>{let a=e.acceleration;if(!a)return;let magnitude=Math.hypot(a.x||0,a.y||0,a.z||0);if(magnitude>20&&Date.now()-lastShake>2500&&!document.querySelector('dialog[open]')){lastShake=Date.now();launch()}});motionActive=true;$('motion').textContent='Lanzamiento al agitar activado';$('motion').disabled=true;$('motion-info').textContent='Agita el teléfono con la mesa abierta para lanzar.'}catch{toast('El sensor no está disponible.')}};
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').hidden=false});$('install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('install').hidden=true}};if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
$('history-count').textContent=history.length;renderPresets();try{init()}catch(e){console.error(e);$('loading').textContent='No se pudo iniciar la mesa 3D. Activa WebGL o prueba Safari/Chrome actualizado.';$('roll').disabled=true}
const mc=document.modelContext;if(mc?.registerTool){try{mc.registerTool({name:'roll_dice',description:'Configura y lanza dados en la mesa; devuelve el resultado cuando se detienen.',inputSchema:{type:'object',properties:{dice:{type:'array',items:{type:'integer',enum:TYPES},minItems:1,maxItems:20},modifier:{type:'integer',minimum:-999,maximum:999}},required:['dice'],additionalProperties:false},execute:async input=>{if(rolling)throw Error('Hay una tirada en curso');if(!input||!Array.isArray(input.dice)||!input.dice.length||input.dice.some(x=>!TYPES.includes(x))||input.dice.reduce((s,t)=>s+(t===100?2:t===1000?3:1),0)>20||input.modifier!==undefined&&(!Number.isInteger(input.modifier)||Math.abs(input.modifier)>999))throw Error('Tirada no válida');pool=[...input.dice];poolColors=[];rollMode='normal';$('roll-mode').value='normal';$('modifier').value=input.modifier??0;syncDice();return await launch()}})}catch{}}

function colorOptions(select,value){for(const[color,name]of PALETTE){let option=document.createElement('option');option.value=color;option.textContent=name;select.append(option)}select.value=value}
function recolorDie(d,color){if(rolling||!PALETTE.some(([c])=>c===color))return;d.color=color;poolColors[d.logicalIndex][d.colorIndex]=color;d.mesh.material.color.set(color);let dark=['#202329','#b51f32'].includes(color);d.edges.material.color.set(dark?'#e7eaf0':'#29303a');d.edges.material.opacity=dark?.24:.16;for(const child of d.group.children){let paint=child.userData.paint;if(paint)child.material.map=tex(paint.value,paint.pips,color)}dirty=true}
function renderDieColors(){const list=$('die-colors');list.replaceChildren();$('color-table').hidden=!dice.length;dice.forEach((d,i)=>{let row=document.createElement('label');row.className='die-color-row';let dot=document.createElement('span');dot.className='color-dot';dot.style.background=d.color;let name=document.createElement('span');name.textContent=`${i+1} · d${d.type}`+(pool[d.logicalIndex]>=100?` ×${d.place}`:'');let select=document.createElement('select');select.setAttribute('aria-label',`Color del dado ${i+1}`);colorOptions(select,d.color);select.disabled=rolling;select.onchange=()=>{recolorDie(d,select.value);dot.style.background=d.color};row.append(dot,name,select);list.append(row)})}
colorOptions($('add-color'),settings.color);$('add-color').onchange=e=>{settings.color=e.target.value;$('color').value=settings.color;persistSettings()};
